#baseURL = "https://jumpstart-frontend.netlify.app/"
#erik's local dev
baseURL = "http://localhost/dev/jumpstart/public"
languageCode = "en-us"
title = "Jumpstart Academy: Building Blocks of the Web"
theme = "learn"
themesdir = "themes"
[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"
  showVisitedLinks = true