baseURL = "https://jumpstart-frontend.netlify.app/"
languageCode = "en-us"
title = "Jumpstart Academy: Building Blocks of the Web"
theme = "learn"
[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"
  showVisitedLinks = false
[build]
  command = "hugo"
  publish = "public"
[build.environment]
  HUGO_VERSION = 1.0.0
